data:
  raw: "data/raw/flights.csv"
  processed: "data/processed/flights_processed.csv"
  split_dir: "data/split"

preprocess:
  handle_missing: true
  remove_outliers: true
  test_size: 0.2
  random_state: 42

experiments:
  experiment_name: "flight_delay_prediction"
  tracking_uri: "http://localhost:5000"
  
models:
  random_forest:
    n_estimators: [50, 100, 200]
    max_depth: [5, 10, 15, null]
    min_samples_split: [2, 5, 10]
    random_state: 42
    
  xgboost:
    n_estimators: [50, 100, 200]
    max_depth: [3, 6, 10]
    learning_rate: [0.01, 0.1, 0.2]
    random_state: 42
    
  logistic_regression:
    C: 1.0
    max_iter: 1000
    random_state: 42
    solver: 'lbfgs'

hyperparameter_tuning:
  max_evals: 20
  cv_folds: 3
  scoring: "f1"